javascript-forms - Junou Lee
junoulee/c1222-code-solutions pull request #45
Opened 2022-12-20 08:54 UTC by junoulee

![image](https://user-images.githubusercontent.com/117887912/208624878-3317c29c-abd9-4be3-b19d-627a5e3cf076.png)
![image](https://user-images.githubusercontent.com/117887912/208624923-c248b99a-742d-4b4a-b6df-37c112bc25fb.png)

2022-12-20 16:55 UTC, junoulee commented
![image](https://user-images.githubusercontent.com/117887912/208722361-5d365f3a-7b0e-47a1-a2a4-e48e7e91d7f9.png)

2022-12-20 16:56 UTC, junoulee commented
![image](https://user-images.githubusercontent.com/117887912/208722697-ba12a37c-c300-4de6-9f71-640cc2df66d2.png)

2022-12-20 19:12 UTC, codingcodymiller requested changes

2022-12-20 19:12 UTC, codingcodymiller commented on javascript-forms/form-values.js
> +var xx = document.querySelector('#contact-form');
You should make a better name for this variable.

2022-12-20 19:12 UTC, codingcodymiller commented on javascript-forms/form-values.js
> +  var object = { name: one, email: two, message: three };
these could use better names too. Get in the habit of giving your variables and functions quality names.

2022-12-21 17:51 UTC, codingcodymiller approved these changes

2022-12-21 18:35 UTC, merged