array-manipulation-2 - Junou Lee
junoulee/c1222-code-solutions pull request #57
Opened 2023-01-03 00:51 UTC by junoulee

![image](https://user-images.githubusercontent.com/117887912/210287925-2ded5c4f-3ae8-4e4a-9dba-e4525b8e1658.png)

2023-01-19 18:16 UTC, codingcodymiller requested changes

2023-01-19 18:16 UTC, codingcodymiller commented on array-manipulation-2/src/chunk.js
> +  if (array.length === 7) {
Why specifically seven? This seems like you have a bug in your process that you are trying to cover up

2023-01-24 23:58 UTC, RobertGardner approved these changes
Some minor suggestions on how to improve the code, but don't worry about them unless you want more practice.

2023-01-24 23:58 UTC, RobertGardner commented on array-manipulation-2/src/chunk.js
> +    return array;
This "works" but the spec says to return a copy of the array.

2023-01-24 23:58 UTC, RobertGardner commented on array-manipulation-2/src/drop-right.js
> +    return array;
Here, too.

2023-01-24 23:58 UTC, RobertGardner commented on array-manipulation-2/src/drop-right.js
> +  for (var i = 0; i <= (array.length - 1) - count; i++) {
It would be more idiomatic in the test expression to use `<` instead of `<=`. To make that work, just remove the `- 1`.

2023-01-24 23:58 UTC, RobertGardner commented on array-manipulation-2/src/drop.js
> +  if (array.length === 0) {
This check isn't actually necessary since the loop on line 9 won't execute if array.length is 0.

2023-01-24 23:58 UTC, RobertGardner commented on array-manipulation-2/src/includes.js
> +  if (array.length === 0) {
This check also isn't really needed.

2023-01-24 23:58 UTC, RobertGardner commented on array-manipulation-2/src/take.js
> +    for (var i = 0; i < count; i++) {
I think you need to worry about if `count` is larger than `array.length`, don't you?

2023-02-02 07:27 UTC, merged